name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy Nodejs app
        uses: appleboy/ssh-action@v01.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.GITCICD_SECRETS}}
          username: ${{secrets.SSH_USER}}




          script: |
            mkdir test
            cd test
            git clone git@github.com/farhansaif.git
            echo 'Deployment Successful to artemis'
