name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy farhansaif.xyz
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}



          script: |

            cd /home/saif/deploy

          git clone https://github.com/overlorde/farhansaif.git

            echo 'Deployment Successful to artemis'
