name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy some app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}




          script: |

            mkdir projects

            cd projects

            git clone https://github.com/overlorde/clox.git

            cd clox

            make

            echo 'Deployment Successful to artemis'
